### ISSUE TITLE
Random classification baseline does not work when using accuracy in constraint strings

### ISSUE THREAD

**Issue by mhyeh** [seldonian-toolkit/Experiments#2]
When constraint strings include ACC, such as `min((ACC | [democrat])/(ACC | [republican]),(ACC | [republican])/(ACC | [democrat])) >= 0.8`, running the random classification baseline will cause an error below:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/experiments/experiments.py", line 285, in run_baseline_trial
    parse_tree.evaluate_constraint(theta=solution,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seldonian/parse_tree/parse_tree.py", line 727, in evaluate_constraint
    self._evaluator_helper(self.root,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seldonian/parse_tree/parse_tree.py", line 779, in _evaluator_helper
    self._evaluator_helper(node.right,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seldonian/parse_tree/parse_tree.py", line 777, in _evaluator_helper
    self._evaluator_helper(node.left,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seldonian/parse_tree/parse_tree.py", line 777, in _evaluator_helper
    self._evaluator_helper(node.left,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seldonian/parse_tree/parse_tree.py", line 768, in _evaluator_helper
    value = node.calculate_value(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/seldonian/parse_tree/nodes.py", line 140, in calculate_value
    value = evaluate_statistic(model,
...
--> 388         raise self._exception
    389     else:
    390         return self._result

AttributeError: 'NoneType' object has no attribute 'ndim'
```

**Comment by austinhoag** [comment]
This is a bug in the Engine. I addressed the problem in this commit: https://github.com/seldonian-toolkit/Engine/commit/e2e6932977f0cca6d59133f2ba974157e70b7d00

It is resolved in v0.7.4 of the seldonian-engine PyPI package
